version: '3.0'

services:
  admin:
      container_name: watson_integration
      build:
        context: .
        dockerfile: docker/local/Dockerfile
      ports:
        - "8000:8000"
      env_file: secret.envvars
      working_dir: /opt/app/project
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/opt/app




